// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkpfnvnnpbfttedatjlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrcGZudm5ucGJmdHRlZGF0amxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NzIxMzMsImV4cCI6MjA4ODU0ODEzM30.pWwtNwFGFhLKB3fu2d4M8hjstbT6whD0oP0qtP31rKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});